/**
 * Runnable interface just contain only one method run(). We need to create new Thread object 
 * and pass the target runnable i.e object of runnable to start new thread. As Thread class
 * implements runnable interface , we can use Thread class object also as target runnable, it 
 * won't throw error.
 * Every thread in java has some name, maybe default name generated by jvm or customized name provided by programmer.
 */
public class MyRunnable {

	public static void main(String[] args) {
		Runnable r1 = new MyRunnableThread();
		//MyThreadNew t1 = new MyThreadNew();
		Thread t = new Thread(r1);
		t.start();
		for(int i = 0 ;i<5 ;i++)
			System.out.println("This is parent thread.." + i);
		//to get name of current executing thread
		System.out.println("Current Thread: "+ Thread.currentThread());
		
	}
}

class MyRunnableThread implements Runnable{
	
	//job of threadn 
	public void run() {
		for(int i = 0 ;i<5 ;i++)
			System.out.println("This is child thread using runnable.." + i);
		
		//strring the name of current executing thread
		Thread.currentThread().setName("MyRunnableThread");
		System.out.println("Current Thread: " + Thread.currentThread().getName());
	}
}

/*class MyThreadNew extends Thread{
	@Override
	public void run() {
		for(int i = 0 ;i<5 ;i++)
			System.out.println("This is child thread using Thread.." + i);
	}
}*/
